apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-web
  namespace: k8s-hacking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-web
  template:
    metadata:
      labels:
        app: shop-web
    spec:
      containers:
      - name: shop
        image: prestashop/prestashop:1.7
        env:
        - name: DB_SERVER
          valueFrom:
            secretKeyRef:
              name: shop-db-secret
              key: db_host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: shop-db-secret
              key: username
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: shop-db-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: shop-db-secret
              key: dbname
        - name: PS_INSTALL_AUTO
          value: "1"
        - name: PS_DOMAIN
          value: "kma.prestashop.vn"
        ports:
        - containerPort: 80